### ISSUE TITLE
Not working because wrong hook name

### ISSUE THREAD

**Issue by cdfa** [sapegin/mrm-tasks#23]
After several hours of debugging my pre-commit hook, I found out it wasn't working, because this task adds a `precommit` hook instead of a `pre-commit` hook.

**Comment by cdfa** [comment]
#22 seems to fix this.

**Comment by sapegin** [comment]
Mind sending a new _working_ PR to fix that?

**Comment by cdfa** [comment]
I was planning on forking #22's master, but I noticed there are failing tests (not just on the patch-1 branch). So I decided not to spend more time on it, because the CI would fail anyway. If this repo's master has no failing test one could rebase on there probably, but I didn't want to get sidetracked too much.
