### ISSUE TITLE
mrm-task-lint-staged does not install husky and lint-staged as dev dependencies

### ISSUE THREAD

**Issue by TabithaLarkin** [sapegin/mrm-tasks#25]
1. Set up package.json with eslint configuration
2. Run `npx mrm lint-staged`
3. Configuration is entered into package.json, but `devDependencies` object is unchanged.

I would expect that these two packages are installed so that when other developers in the organisation run `npm i` that both husky and lint-staged would be installed for them.

**Comment by sapegin** [comment]
This should happen:

https://github.com/sapegin/mrm-tasks/blob/bb7c344aba762ecabbc0f48748a0b23b47553e29/packages/mrm-task-lint-staged/index.js#L4

And I never had issues with that myself, so you'll need to debug the script to see when it's failing.
