### ISSUE TITLE
ESLint task: .eslintignore is not necessary

### ISSUE THREAD

**Issue by dfernandez79** [sapegin/mrm-tasks#26]
By default Eslint ignores `node_modules`, adding it too `.eslintignore` is not necessary.

See: https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories

**Comment by sapegin** [comment]
Read further:

> Important: Note that node_modules directories in, for example, a packages directory in a mono repo are not ignored by default and need to be added to .eslintignore explicitly.
