### ISSUE TITLE
lint-staged task has 'eslint --fix' but eslint is not installed locally

### ISSUE THREAD

**Issue by osdevisnot** [sapegin/mrm-tasks#3]
Hi @sapegin, wanted to mention that this package is awesome ❤️ ❤️ .

One small thing I noticed is, the lint-staged task has 'eslint --fix' in npm scripts but eslint package is not installed locally. This fails if user does not have eslint installed globally.

I will create a PR for this later if adding the package dep seems correct solution.

**Comment by sapegin** [comment]
I think we should do the opposite: add eslint to lint-staged only if it’s installed. And eventually add other tools like stylelint, jest, etc.

**Comment by sapegin** [comment]
The first step is done at 1addaf5820e892838882cd96aed96223582aa2ca.

**Comment by sapegin** [comment]
I'm going to close this: lint-staged task supports Prettier, ESLint and Stylelint now.
