### ISSUE TITLE
Remove `git add` from lint-staged task

### ISSUE THREAD

**Issue by okonet** [sapegin/mrm-tasks#52]
Since [v10](https://github.com/okonet/lint-staged/releases/tag/v10.0.0) listing `git add` as a task is deprecated and will produce a warning. So it should be removed from the task.

@sapegin should it be major or minor bump you think?

Related issues: https://github.com/okonet/lint-staged/issues/775

**Comment by sapegin** [comment]
I think we should [“require” lint-staged 10](https://github.com/sapegin/mrm-tasks/blob/40d49c35c164030497bfae1e0a404e6ac9275671/packages/mrm-task-lint-staged/index.js#L4) in the dependencies and remove `git add` from the existing config. And then it will upgrade the config correctly, so minor is fine I guess.

**Comment by okonet** [comment]
According to test suite, it already removes it (not sure how this works thought): 

https://github.com/sapegin/mrm-tasks/pull/53/files#diff-35fca8a52dafddf36bb3af64a2f3a23dR200-R219

and 

https://github.com/sapegin/mrm-tasks/blob/9ee30823a744261ceccef4b45588b55bf13cdc35/packages/mrm-task-lint-staged/index.spec.js#L324-L343

**Comment by sapegin** [comment]
I'm a bit confused too with this ;-/

**Comment by okonet** [comment]
But seems to work :)

**Comment by sapegin** [comment]
Check my comment in the PR: looks like it's removing more than just `git add` ;-/
